version: '3.8'

# Shared Airflow config (ONE image for everything)
x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: DOCKERFILE
  image: custom-airflow:latest
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    PYTHONPATH: "/opt/airflow"
  volumes:
    - ./:/opt/airflow
    - ./pipeline_logs:/logs
    - /var/run/docker.sock:/var/run/docker.sock

  depends_on:
    db:
      condition: service_healthy

services:

    
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      # LISTENERS: The actual ports opened inside the container
      KAFKA_LISTENERS: 'INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093'
      # ADVERTISED: The addresses Kafka tells Spark/Producers to use
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:9092,EXTERNAL://localhost:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  
  # PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Airflow Init (runs once)
  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    command: >
      bash -c "
      airflow db init &&
      airflow users create \
      --username ${AIRFLOW_ADMIN_USER} \
      --firstname ${AIRFLOW_ADMIN_FIRSTNAME} \
      --lastname ${AIRFLOW_ADMIN_LASTNAME} \
      --role Admin \
      --email ${AIRFLOW_ADMIN_EMAIL} \
      --password ${AIRFLOW_ADMIN_PASSWORD}
      "

  # Scheduler (runs your DAGs)
  scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: scheduler
   
  # Web UI
  webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    ports:
      - "8083:8080"
    depends_on:
      - scheduler
    command: webserver
  
  spark:
    image: apache/spark:3.5.0
    container_name: spark
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./spark_jobs:/opt/spark_jobs
      - ./utils:/opt/spark_jobs/utils
      - ./storage:/opt/spark_jobs/storage
      - ./.env:/opt/spark_jobs/.env
      - ./config.py:/opt/spark_jobs/config.py
      - ./data:/opt/spark_jobs/data 
      - ./pipeline_logs:/logs
      - ./spark_jobs/checkpoints:/opt/spark_jobs/checkpoints
      - ./ivy_cache:/home/spark/.ivy2
   